#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO.Views.Report
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class OrdPaymRappel : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
        #line 3 "..\..\Views\Report\OrdPaymRappel.cshtml"
            
  public string host { get; set; }
  public dynamic q1 { get; set; }
  public dynamic em { get; set; }
  public System.Web.Mvc.UrlHelper url { get; set; }

        #line default
        #line hidden
        
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

WriteLiteral(@"
<style>
  table {
    border-collapse: collapse;
    border: 1px solid gray;
  }

  td, span, th {
    font-size: .8em;
    font-family: ""Segoe UI"", Verdana, Helvetica, Sans-Serif;
    text-align: left;
  }

  span {
    font-style: italic;
  }

  th {
    font-size: .7em;
  }

  .em {
    color: #fff;
    font-size: .7em;
  }

  .r {
    text-align: right;
  }
</style>
<table>
  <tr>
    <th>Номер</th>
    <th>Получатель</th>
    <th>Договор</th>
    <th>Сумма</th>
    <th>Валюта</th>
    <th>Дата составления</th>
  </tr>
");

            
            #line 48 "..\..\Views\Report\OrdPaymRappel.cshtml"
  
            
            #line default
            #line hidden
            
            #line 48 "..\..\Views\Report\OrdPaymRappel.cshtml"
    
    foreach (var r in q1)
    {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n\r\n      <td><a");

WriteAttribute("href", Tuple.Create(" href=\'", 865), Tuple.Create("\'", 955)
            
            #line 53 "..\..\Views\Report\OrdPaymRappel.cshtml"
, Tuple.Create(Tuple.Create("", 872), Tuple.Create<System.Object, System.Int32>(url.RouteUrl("Default", new { action = "opcs", id = r.id, s = r.StateID }, "http")
            
            #line default
            #line hidden
, 872), false)
);

WriteLiteral(">");

            
            #line 53 "..\..\Views\Report\OrdPaymRappel.cshtml"
                                                                                                   Write(r.id);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n      <td>");

            
            #line 54 "..\..\Views\Report\OrdPaymRappel.cshtml"
     Write(r.Receiver);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 55 "..\..\Views\Report\OrdPaymRappel.cshtml"
      Write(r.DogovorID == null ? r.Dogovor : (r.DogName + (r.DogDate != null ? " от " + r.DogDate.ToShortDateString() + "г." : "")));

            
            #line default
            #line hidden
WriteLiteral("&nbsp;</td>\r\n      <td");

WriteLiteral(" class=\"r\"");

WriteLiteral(">");

            
            #line 56 "..\..\Views\Report\OrdPaymRappel.cshtml"
                Write(r.Qty == null ? "" : string.Format("{0:N2}", r.Qty));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 57 "..\..\Views\Report\OrdPaymRappel.cshtml"
     Write(r.FundName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 58 "..\..\Views\Report\OrdPaymRappel.cshtml"
     Write(r.DateCreate.ToString("dd.MM.yy"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    </tr>\r\n");

            
            #line 60 "..\..\Views\Report\OrdPaymRappel.cshtml"
    }
  
            
            #line default
            #line hidden
WriteLiteral("\r\n</table>\r\n<br>\r\n<span");

WriteLiteral(" class=\"em\"");

WriteLiteral(">");

            
            #line 64 "..\..\Views\Report\OrdPaymRappel.cshtml"
            Write(em);

            
            #line default
            #line hidden
WriteLiteral("</span>");

        }
    }
}
#pragma warning restore 1591
