#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO.Areas.Code.Views.CorpEvents
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class Rappel : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
        #line 3 "..\..\Areas\Code\Views\CorpEvents\Rappel.cshtml"
            
  public string host { get; set; }
  public dynamic q1 { get; set; }
  public dynamic em { get; set; }
  public string nb { get; set; }

        #line default
        #line hidden
        
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

WriteLiteral(@"
<style>
  table {
    border-collapse: collapse;
    border: 1px solid gray;
  }

  td, span, th {
    font-size: .8em;
    font-family: ""Segoe UI"", Verdana, Helvetica, Sans-Serif;
    text-align: left;
    border: 1px solid gray;
  }

  span {
    font-style: italic;
  }

  th {
    font-size: .7em;
  }

  .em {
    color: #fff;
    font-size: .7em;
  }

  .r {
    text-align: right;
  }
</style>
<table>
  <tr>
    <th>П/п</th>
    <th>Клиент</th>
    <th>Номер</th>
    <th>Стратегия</th>
    <th>Тип документа</th>
    <th>Примечание</th>
    <th>Дата получения</th>
    <th>Дата расторжения</th>
    <th>Сумма</th>
    <th>КМ</th>
    <th>УА</th>
    <th>БУ</th>
    <th>РЦ</th>
  </tr>
");

            
            #line 56 "..\..\Areas\Code\Views\CorpEvents\Rappel.cshtml"
  
            
            #line default
            #line hidden
            
            #line 56 "..\..\Areas\Code\Views\CorpEvents\Rappel.cshtml"
    
    foreach (var r in q1)
    {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n      <td><a");

WriteAttribute("href", Tuple.Create(" href=\'", 1018), Tuple.Create("\'", 1092)
, Tuple.Create(Tuple.Create("", 1025), Tuple.Create("http://", 1025), true)
            
            #line 60 "..\..\Areas\Code\Views\CorpEvents\Rappel.cshtml"
, Tuple.Create(Tuple.Create("", 1032), Tuple.Create<System.Object, System.Int32>(host
            
            #line default
            #line hidden
, 1032), false)
, Tuple.Create(Tuple.Create("", 1037), Tuple.Create("/code/CorpEvents/getEnreg?id=", 1037), true)
            
            #line 60 "..\..\Areas\Code\Views\CorpEvents\Rappel.cshtml"
, Tuple.Create(Tuple.Create("", 1066), Tuple.Create<System.Object, System.Int32>(r.PID
            
            #line default
            #line hidden
, 1066), false)
, Tuple.Create(Tuple.Create("", 1072), Tuple.Create("&t=", 1072), true)
            
            #line 60 "..\..\Areas\Code\Views\CorpEvents\Rappel.cshtml"
, Tuple.Create(Tuple.Create("", 1075), Tuple.Create<System.Object, System.Int32>((int)r.t
            
            #line default
            #line hidden
, 1075), false)
, Tuple.Create(Tuple.Create("", 1086), Tuple.Create("&a=", 1086), true)
            
            #line 60 "..\..\Areas\Code\Views\CorpEvents\Rappel.cshtml"
   , Tuple.Create(Tuple.Create("", 1089), Tuple.Create<System.Object, System.Int32>(nb
            
            #line default
            #line hidden
, 1089), false)
);

WriteLiteral(">");

            
            #line 60 "..\..\Areas\Code\Views\CorpEvents\Rappel.cshtml"
                                                                                   Write(r.Num);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n      <td>");

            
            #line 61 "..\..\Areas\Code\Views\CorpEvents\Rappel.cshtml"
     Write(r.ClientName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 62 "..\..\Areas\Code\Views\CorpEvents\Rappel.cshtml"
     Write(r.Portal);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 63 "..\..\Areas\Code\Views\CorpEvents\Rappel.cshtml"
     Write(r.Strategy);

            
            #line default
            #line hidden
            
            #line 63 "..\..\Areas\Code\Views\CorpEvents\Rappel.cshtml"
                 Write(!string.IsNullOrEmpty(r.StrategyP) ? (" (" + r.StrategyP + ")") : "");

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 64 "..\..\Areas\Code\Views\CorpEvents\Rappel.cshtml"
     Write(r.DTName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 65 "..\..\Areas\Code\Views\CorpEvents\Rappel.cshtml"
     Write(r.Remarque);

            
            #line default
            #line hidden
WriteLiteral("&nbsp;</td>\r\n      <td>");

            
            #line 66 "..\..\Areas\Code\Views\CorpEvents\Rappel.cshtml"
      Write(r.RecuDate == null ? "&nbsp;" : r.RecuDate.ToString("dd.MM.yyyy"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 67 "..\..\Areas\Code\Views\CorpEvents\Rappel.cshtml"
      Write(r.CancelDate == null ? "&nbsp;" : r.CancelDate.ToString("dd.MM.yyyy"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td");

WriteLiteral(" class=\"r\"");

WriteLiteral(">");

            
            #line 68 "..\..\Areas\Code\Views\CorpEvents\Rappel.cshtml"
                Write(r.Qty == null ? "&nbsp;" : string.Format("{0:N2}", r.Qty));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>&nbsp;&nbsp;");

            
            #line 69 "..\..\Areas\Code\Views\CorpEvents\Rappel.cshtml"
                 Write(r.IsKM);

            
            #line default
            #line hidden
WriteLiteral("&nbsp;&nbsp;</td>\r\n      <td>&nbsp;&nbsp;");

            
            #line 70 "..\..\Areas\Code\Views\CorpEvents\Rappel.cshtml"
                 Write(r.IsUA);

            
            #line default
            #line hidden
WriteLiteral("&nbsp;&nbsp;</td>\r\n      <td>&nbsp;&nbsp;");

            
            #line 71 "..\..\Areas\Code\Views\CorpEvents\Rappel.cshtml"
                 Write(r.IsBU);

            
            #line default
            #line hidden
WriteLiteral("&nbsp;&nbsp;</td>\r\n      <td>&nbsp;&nbsp;");

            
            #line 72 "..\..\Areas\Code\Views\CorpEvents\Rappel.cshtml"
                 Write(r.IsRC);

            
            #line default
            #line hidden
WriteLiteral("&nbsp;&nbsp;</td>\r\n    </tr>\r\n");

            
            #line 74 "..\..\Areas\Code\Views\CorpEvents\Rappel.cshtml"
    }
  
            
            #line default
            #line hidden
WriteLiteral("\r\n</table>\r\n<br>\r\n<span");

WriteLiteral(" class=\"em\"");

WriteLiteral(">");

            
            #line 78 "..\..\Areas\Code\Views\CorpEvents\Rappel.cshtml"
            Write(em);

            
            #line default
            #line hidden
WriteLiteral("</span>");

        }
    }
}
#pragma warning restore 1591
