#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO.Areas.Code.Views.CorpEvents
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class SampleTemplate : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
        #line 3 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
            
  public dynamic q1 { get; set; }
  public dynamic q2 { get; set; }
  public Guid id { get; set; }
  public MO.Areas.Code.Models.numDep t { get; set; }
  public string host { get; set; }
  public string descr { get; set; }

        #line default
        #line hidden
        
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

WriteLiteral(@"
<style>
  table {
    border-collapse: collapse;
    border: 1px solid gray;
  }

  td, span, th {
    font-size: .8em;
    font-family: ""Segoe UI"", Verdana, Helvetica, Sans-Serif;
    text-align: left;
  }

  span {
    font-style: italic;
  }

  th {
    font-size: .7em;
  }
</style>
<span>Уважаемый коллега,<br>
");

            
            #line 33 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
  
            
            #line default
            #line hidden
            
            #line 33 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
   if (descr != "")
  {

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral("<b>Вам отказано в исполнении поручения</b>");

WriteLiteral("<br />\r\n");

            
            #line 36 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
  }

            
            #line default
            #line hidden
WriteLiteral("  ");

            
            #line 37 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
   if (t == MO.Areas.Code.Models.numDep.IsAll)
  {
    
            
            #line default
            #line hidden
            
            #line 39 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
Write(q2.str);

            
            #line default
            #line hidden
            
            #line 39 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
            
  }
  else if (t != MO.Areas.Code.Models.numDep.IsSS)
  {

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral("просим ");

            
            #line 43 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
            Write(q2.str);

            
            #line default
            #line hidden
WriteLiteral(" клиента по <a");

WriteAttribute("href", Tuple.Create(" href=\'", 905), Tuple.Create("\'", 986)
, Tuple.Create(Tuple.Create("", 912), Tuple.Create("http://", 912), true)
            
            #line 43 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
, Tuple.Create(Tuple.Create("", 919), Tuple.Create<System.Object, System.Int32>(host
            
            #line default
            #line hidden
, 919), false)
, Tuple.Create(Tuple.Create("", 924), Tuple.Create("/code/CorpEvents/confirmEnrDet?id=", 924), true)
            
            #line 43 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
            , Tuple.Create(Tuple.Create("", 958), Tuple.Create<System.Object, System.Int32>(id
            
            #line default
            #line hidden
, 958), false)
, Tuple.Create(Tuple.Create("", 961), Tuple.Create("&t=", 961), true)
            
            #line 43 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
                   , Tuple.Create(Tuple.Create("", 964), Tuple.Create<System.Object, System.Int32>((int)t
            
            #line default
            #line hidden
, 964), false)
, Tuple.Create(Tuple.Create("", 973), Tuple.Create("&a=", 973), true)
            
            #line 43 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
                              , Tuple.Create(Tuple.Create("", 976), Tuple.Create<System.Object, System.Int32>(q2.NameTo
            
            #line default
            #line hidden
, 976), false)
);

WriteLiteral(">ссылке</a>");

WriteLiteral("\r\n");

            
            #line 44 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
  }

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n<table>\r\n  <tr>\r\n    <th>Клиент</th>\r\n    <td>");

            
            #line 49 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
   Write(q1.ClientName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n  </tr>\r\n  <tr>\r\n    <th>Код клиента</th>\r\n    <td>");

            
            #line 53 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
   Write(q1.ClientCode);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n  </tr>\r\n  <tr>\r\n    <th>№ Договора</th>\r\n    <td>");

            
            #line 57 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
   Write(q1.trNameBrief);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n  </tr>\r\n  <tr>\r\n    <th>Дата договора</th>\r\n    <td>");

            
            #line 61 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
   Write(q1.DateStart.ToString("dd.MM.yy"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n  </tr>\r\n  <tr>\r\n    <th>Документ</th>\r\n    <td>");

            
            #line 65 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
   Write(q1.DTName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n  </tr>\r\n  <tr>\r\n    <th>Оригинал</th>\r\n    <td>");

            
            #line 69 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
    Write(q1.Original ?? false ? "Да" : "Нет");

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n  </tr>\r\n  <tr>\r\n    <th>Клиентский</th>\r\n    <td>");

            
            #line 73 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
   Write(q1.ClnManager);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n  </tr>\r\n");

WriteLiteral("\r\n  <tr>\r\n    <th");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">Сроки исполнения (Дата исполнения)</th>\r\n  </tr>\r\n  <tr>\r\n    <th>По договору</t" +
"h>\r\n    <td>");

            
            #line 84 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
   Write(q1.DaysDog);

            
            #line default
            #line hidden
WriteLiteral(" дн. (");

            
            #line 84 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
                    Write(q1.DateDog.ToString("dd.MM.yy"));

            
            #line default
            #line hidden
WriteLiteral(")</td>\r\n  </tr>\r\n  <tr>\r\n    <th>По документу</th>\r\n    <td>");

            
            #line 88 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
   Write(q1.DaysDoc);

            
            #line default
            #line hidden
WriteLiteral(" дн. (");

            
            #line 88 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
                    Write(q1.DateDoc.ToString("dd.MM.yy"));

            
            #line default
            #line hidden
WriteLiteral(")</td>\r\n  </tr>\r\n  <tr>\r\n    <th>Сумма</th>\r\n    <td>");

            
            #line 92 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
    Write(q1.Qty == null ? "" : string.Format("{0:N2}", q1.Qty));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n  </tr>\r\n  <tr>\r\n    <th>Примечание</th>\r\n    <td>");

            
            #line 96 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
   Write(q1.Remarque);

            
            #line default
            #line hidden
WriteLiteral("&nbsp;</td>\r\n  </tr>\r\n");

            
            #line 98 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
  
            
            #line default
            #line hidden
            
            #line 98 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
   if (descr != "")
  {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n      <th>ОТКАЗ</th>\r\n      <td>");

            
            #line 102 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
     Write(descr);

            
            #line default
            #line hidden
WriteLiteral("&nbsp;</td>\r\n    </tr>\r\n");

            
            #line 104 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
  }

            
            #line default
            #line hidden
WriteLiteral("  ");

            
            #line 105 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
   if (!String.IsNullOrWhiteSpace(q1.FileName))
  {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n      <th>Файл</th>\r\n      <td>");

            
            #line 109 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
      Write(string.Format("<a href='http://{1}/code/corpevents/GetFileEnr?data={2}'>{0}</a>", q1.FileName, host, System.Web.HttpUtility.UrlEncode(q1.FileName)));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    </tr>\r\n");

            
            #line 111 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
  }

            
            #line default
            #line hidden
WriteLiteral("</table>\r\n<br>\r\n");

            
            #line 114 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
 if (t != MO.Areas.Code.Models.numDep.IsAll && t != MO.Areas.Code.Models.numDep.IsSS)
{

            
            #line default
            #line hidden
WriteLiteral("  <span><a");

WriteAttribute("href", Tuple.Create(" href=\'", 2607), Tuple.Create("\'", 2688)
, Tuple.Create(Tuple.Create("", 2614), Tuple.Create("http://", 2614), true)
            
            #line 116 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
, Tuple.Create(Tuple.Create("", 2621), Tuple.Create<System.Object, System.Int32>(host
            
            #line default
            #line hidden
, 2621), false)
, Tuple.Create(Tuple.Create("", 2626), Tuple.Create("/code/CorpEvents/refusalEnrDet?id=", 2626), true)
            
            #line 116 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
, Tuple.Create(Tuple.Create("", 2660), Tuple.Create<System.Object, System.Int32>(id
            
            #line default
            #line hidden
, 2660), false)
, Tuple.Create(Tuple.Create("", 2663), Tuple.Create("&t=", 2663), true)
            
            #line 116 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
, Tuple.Create(Tuple.Create("", 2666), Tuple.Create<System.Object, System.Int32>((int)t
            
            #line default
            #line hidden
, 2666), false)
, Tuple.Create(Tuple.Create("", 2675), Tuple.Create("&a=", 2675), true)
            
            #line 116 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
 , Tuple.Create(Tuple.Create("", 2678), Tuple.Create<System.Object, System.Int32>(q2.NameTo
            
            #line default
            #line hidden
, 2678), false)
);

WriteLiteral(">в случае невозможности исполнения распоряжения просьба перейти по ссылке отказа " +
"и объяснить причину ОТКАЗа</a></span>\r\n");

WriteLiteral("  <br />\r\n");

WriteLiteral("  <span>Подпись: Мидл-офис</span>\r\n");

            
            #line 119 "..\..\Areas\Code\Views\CorpEvents\SampleTemplate.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
