#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO.Areas.Code.Views.Leave
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class SendConfirmed : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
        #line 3 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
            
  public dynamic q { get; set; }
  public string host { get; set; }
  public string email { get; set; }

        #line default
        #line hidden
        
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

WriteLiteral(@"
<style>
  table {
    border-collapse: collapse;
    border: 1px solid gray;
  }

  td, span, th {
    font-size: .8em;
    font-family: Verdana, Helvetica, Sans-Serif;
    text-align: left;
  }

  span {
    font-style: italic;
  }

  th {
    font-size: .7em;
  }
</style>
<h3>Заявление на отпуск</h3>
<table>
  <tr>
    <th>Сотрудник</th>
    <td>");

            
            #line 33 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
   Write(q.Name1);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n  </tr>\r\n  <tr>\r\n    <th>Вид отпуска</th>\r\n    <td>");

            
            #line 37 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
   Write(q.TypeName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n  </tr>\r\n  <tr>\r\n    <th>Период</th>\r\n    <td>");

            
            #line 41 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
   Write(q.DateB.ToString("dd.MM.yyyy"));

            
            #line default
            #line hidden
WriteLiteral(" - ");

            
            #line 41 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
                                     Write(q.DateE.ToString("dd.MM.yyyy"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n  </tr>\r\n  <tr>\r\n    <th>Календарных дней</th>\r\n    <td>");

            
            #line 45 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
   Write(q.Days.ToString());

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n  </tr>\r\n");

            
            #line 47 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
  
            
            #line default
            #line hidden
            
            #line 47 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
   if (!string.IsNullOrEmpty(q.Comment1))
  {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n      <th>Примечание</th>\r\n      <td>");

            
            #line 51 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
     Write(q.Comment1);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    </tr>\r\n");

            
            #line 53 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
  }

            
            #line default
            #line hidden
WriteLiteral("  <tr>\r\n    <th>Обязанности будут возлагаться на</th>\r\n    <td>");

            
            #line 56 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
   Write(q.Name2);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n  </tr>\r\n  <tr>\r\n    <th>");

            
            #line 59 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
         if (q.Sign4 == null)
        {

            
            #line default
            #line hidden
WriteLiteral("      ");

WriteLiteral("Требует согласования\r\n");

            
            #line 62 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
          }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("      ");

WriteLiteral("Согласовано\r\n");

            
            #line 66 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
          }
            
            #line default
            #line hidden
WriteLiteral("</th>\r\n    <td>");

            
            #line 67 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
   Write(q.Name4);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n  </tr>\r\n");

            
            #line 69 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
  
            
            #line default
            #line hidden
            
            #line 69 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
   if (!string.IsNullOrEmpty(q.Comment4))
  {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n      <th>Примечание</th>\r\n      <td>");

            
            #line 73 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
     Write(q.Comment4);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    </tr>\r\n");

            
            #line 75 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
  }

            
            #line default
            #line hidden
WriteLiteral("  ");

            
            #line 76 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
   if (!string.IsNullOrEmpty(q.Name5))
  {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n      <th>");

            
            #line 79 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
           if (q.Sign5 == null)
          {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("Требует согласования\r\n");

            
            #line 82 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
          }
          else
          {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("Согласовано\r\n");

            
            #line 86 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
          }
            
            #line default
            #line hidden
WriteLiteral("</th>\r\n      <td>");

            
            #line 87 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
     Write(q.Name5);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    </tr>\r\n");

            
            #line 89 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
        if (!string.IsNullOrEmpty(q.Comment5))
        {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n      <th>Примечание</th>\r\n      <td>");

            
            #line 93 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
     Write(q.Comment5);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    </tr>\r\n");

            
            #line 95 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
        }
  }

            
            #line default
            #line hidden
WriteLiteral("</table>\r\n<p");

WriteLiteral(" style=\"color: white; font-style: italic\"");

WriteLiteral(">");

            
            #line 98 "..\..\Areas\Code\Views\Leave\SendConfirmed.cshtml"
                                       Write(email);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

        }
    }
}
#pragma warning restore 1591
