#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO.Areas.Code.Views.Jur
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class warrantCourriel : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
        #line 3 "..\..\Areas\Code\Views\Jur\warrantCourriel.cshtml"
            
  public dynamic q { get; set; }
  public string host { get; set; }

        #line default
        #line hidden
        
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

WriteLiteral(@"
<style>
  table
  {
    border-collapse: collapse;
    border: 1px solid gray;
  }

  td, span, th
  {
    font-size: .8em;
    font-family: Verdana, Helvetica, Sans-Serif;
    text-align: left;
  }

  span
  {
    font-style: italic;
  }

  th
  {
    font-size: .7em;
  }
</style>
<h3>������������, ���������� ����� ������ � �����</h3>
<table");

WriteLiteral(" width=\"100%\"");

WriteLiteral(">\r\n  <tr>\r\n    <th>�����</th>\r\n    <th>���� ������</th>\r\n    <th>����������</th>\r" +
"\n    <th>����������</th>\r\n    <th>����� ��������������</th>\r\n    <th>�������</th" +
">\r\n    <th>���� ��������</th>\r\n    <th>��������</th>\r\n  </tr>\r\n");

            
            #line 44 "..\..\Areas\Code\Views\Jur\warrantCourriel.cshtml"
  
            
            #line default
            #line hidden
            
            #line 44 "..\..\Areas\Code\Views\Jur\warrantCourriel.cshtml"
   foreach (var qq in q)
  {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n      <td>");

            
            #line 47 "..\..\Areas\Code\Views\Jur\warrantCourriel.cshtml"
     Write(qq.Nomer);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 48 "..\..\Areas\Code\Views\Jur\warrantCourriel.cshtml"
     Write(qq.DateB.ToString("dd.MM.yy"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 49 "..\..\Areas\Code\Views\Jur\warrantCourriel.cshtml"
     Write(qq.Confidant);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 50 "..\..\Areas\Code\Views\Jur\warrantCourriel.cshtml"
     Write(qq.Principal);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 51 "..\..\Areas\Code\Views\Jur\warrantCourriel.cshtml"
     Write(qq.Place);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 52 "..\..\Areas\Code\Views\Jur\warrantCourriel.cshtml"
     Write(qq.Functions);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 53 "..\..\Areas\Code\Views\Jur\warrantCourriel.cshtml"
      Write(qq.DateE != null ? qq.DateE.ToString("dd.MM.yy") : "");

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td><a");

WriteAttribute("href", Tuple.Create(" href=\'", 1066), Tuple.Create("\'", 1124)
, Tuple.Create(Tuple.Create("", 1073), Tuple.Create("http://", 1073), true)
            
            #line 54 "..\..\Areas\Code\Views\Jur\warrantCourriel.cshtml"
, Tuple.Create(Tuple.Create("", 1080), Tuple.Create<System.Object, System.Int32>(host
            
            #line default
            #line hidden
, 1080), false)
, Tuple.Create(Tuple.Create("", 1085), Tuple.Create("/code/jur/confirmCloseWarrant?id=", 1085), true)
            
            #line 54 "..\..\Areas\Code\Views\Jur\warrantCourriel.cshtml"
, Tuple.Create(Tuple.Create("", 1118), Tuple.Create<System.Object, System.Int32>(qq.ID
            
            #line default
            #line hidden
, 1118), false)
);

WriteLiteral(">�������</a></td>\r\n    </tr>\r\n");

            
            #line 56 "..\..\Areas\Code\Views\Jur\warrantCourriel.cshtml"
  }

            
            #line default
            #line hidden
WriteLiteral("</table>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
