#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO.Areas.Code.Views.Envoi
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class riskMapCourriel : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
        #line 3 "..\..\Areas\Code\Views\Envoi\riskMapCourriel.cshtml"
            
  public dynamic q { get; set; }
  public int i { get; set; }

        #line default
        #line hidden
        
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

WriteLiteral(@"
<style>
  table
  {
    border-collapse: collapse;
    border: 1px solid gray;
  }

  td, span, th
  {
    font-size: .8em;
    font-family: Verdana, Helvetica, Sans-Serif;
    text-align: left;
  }

  span
  {
    font-style: italic;
  }

  th
  {
    font-size: .7em;
  }
</style>
<h4>Дирекция риск-менеджмента обращает внимание на необходимость соблюдения следующих операционных контролей</h4>
<table>
  <tr>
    <th>Структурное подразделение</th>
    <th>Бизнес процесс</th>
    ");

WriteLiteral("\r\n    <th>Риск наименование</th>\r\n    ");

WriteLiteral("\r\n    <th>");

            
            #line 45 "..\..\Areas\Code\Views\Envoi\riskMapCourriel.cshtml"
    Write(i == 0 ? "Цель" : "Контроль");

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n");

WriteLiteral("    ");

            
            #line 46 "..\..\Areas\Code\Views\Envoi\riskMapCourriel.cshtml"
Write(i == 0 ? "<th>Владелец цели</th>" : "");

            
            #line default
            #line hidden
WriteLiteral("\r\n    <th>Владелец контроля</th>\r\n  </tr>\r\n");

            
            #line 49 "..\..\Areas\Code\Views\Envoi\riskMapCourriel.cshtml"
  
            
            #line default
            #line hidden
            
            #line 49 "..\..\Areas\Code\Views\Envoi\riskMapCourriel.cshtml"
   foreach (var qq in q)
  {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n      <td>");

            
            #line 52 "..\..\Areas\Code\Views\Envoi\riskMapCourriel.cshtml"
     Write(qq.Dep);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 53 "..\..\Areas\Code\Views\Envoi\riskMapCourriel.cshtml"
     Write(qq.BisProc);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      ");

WriteLiteral("\r\n      <td>");

            
            #line 55 "..\..\Areas\Code\Views\Envoi\riskMapCourriel.cshtml"
     Write(qq.RiskName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      ");

WriteLiteral("\r\n      <td>");

            
            #line 62 "..\..\Areas\Code\Views\Envoi\riskMapCourriel.cshtml"
     Write(qq.c1);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

WriteLiteral("      ");

            
            #line 63 "..\..\Areas\Code\Views\Envoi\riskMapCourriel.cshtml"
  Write(i == 0 ? "<td>" + @qq.PossesseurBut + "</td>" : "");

            
            #line default
            #line hidden
WriteLiteral("\r\n      <td>");

            
            #line 64 "..\..\Areas\Code\Views\Envoi\riskMapCourriel.cshtml"
     Write(qq.PossesseurControl);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    </tr>\r\n");

            
            #line 66 "..\..\Areas\Code\Views\Envoi\riskMapCourriel.cshtml"
  }

            
            #line default
            #line hidden
WriteLiteral("</table>\r\n<br>\r\n<span>Дирекция риск-менеджмента</span>\r\n");

        }
    }
}
#pragma warning restore 1591
