#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO.Areas.Code.Views.RegDoc
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class regdocCourriel : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
        #line 3 "..\..\Areas\Code\Views\RegDoc\regdocCourriel.cshtml"
            
  public dynamic q { get; set; }
  public string host { get; set; }
  public string email { get; set; }

        #line default
        #line hidden
        
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

WriteLiteral(@"
<style>
  table {
    border-collapse: collapse;
    border: 1px solid gray;
  }

  td, span, th {
    font-size: .8em;
    font-family: Verdana, Helvetica, Sans-Serif;
    text-align: left;
  }

  span {
    font-style: italic;
  }

  th {
    font-size: .7em;
  }
</style>
<h3>Журнал исполнения поручений</h3>
<table");

WriteLiteral(" width=\"100%\"");

WriteLiteral(@">
  <tr>
    <th>Дата регистрации</th>
    <th>Регистрационный номер</th>
    <th>Вид документа</th>
    <th>Тема документа</th>
    <th>Резолюция</th>
    <th>Кем направлен</th>
    <th>Исполнители</th>
    <th>Для ознакомления</th>
    <th>Срок исполнения</th>
    <th>Входящий документ</th>
    <th>Примечание</th>
  </tr>
");

            
            #line 44 "..\..\Areas\Code\Views\RegDoc\regdocCourriel.cshtml"
  
            
            #line default
            #line hidden
            
            #line 44 "..\..\Areas\Code\Views\RegDoc\regdocCourriel.cshtml"
   foreach (var qq in q)
  {

            
            #line default
            #line hidden
WriteLiteral("    <tr");

WriteAttribute("style", Tuple.Create(" style=\"", 912), Tuple.Create("\"", 1022)
, Tuple.Create(Tuple.Create("", 920), Tuple.Create("color:", 920), true)
            
            #line 46 "..\..\Areas\Code\Views\RegDoc\regdocCourriel.cshtml"
, Tuple.Create(Tuple.Create("", 926), Tuple.Create<System.Object, System.Int32>(qq.TDate < DateTime.Today ? "red" : qq.TDate < DateTime.Today.AddDays(7) ? "maroon" : "black"
            
            #line default
            #line hidden
, 926), false)
);

WriteLiteral(">\r\n      <td>");

            
            #line 47 "..\..\Areas\Code\Views\RegDoc\regdocCourriel.cshtml"
     Write(qq.ODate.ToString("dd.MM.yy"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 48 "..\..\Areas\Code\Views\RegDoc\regdocCourriel.cshtml"
     Write(qq.RegNum);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 49 "..\..\Areas\Code\Views\RegDoc\regdocCourriel.cshtml"
     Write(qq.TypeName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 50 "..\..\Areas\Code\Views\RegDoc\regdocCourriel.cshtml"
     Write(qq.Theme);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 51 "..\..\Areas\Code\Views\RegDoc\regdocCourriel.cshtml"
      Write(qq.Resolution ?? "");

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 52 "..\..\Areas\Code\Views\RegDoc\regdocCourriel.cshtml"
     Write(qq.Directed);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 53 "..\..\Areas\Code\Views\RegDoc\regdocCourriel.cshtml"
     Write(qq.EmailToName);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 53 "..\..\Areas\Code\Views\RegDoc\regdocCourriel.cshtml"
                     Write(qq.EmailCcName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 54 "..\..\Areas\Code\Views\RegDoc\regdocCourriel.cshtml"
      Write(qq.IsAcquaintance == true ? "Да" : "");

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 55 "..\..\Areas\Code\Views\RegDoc\regdocCourriel.cshtml"
      Write(qq.TDate == null ? "" : qq.TDate.ToString("dd.MM.yy"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 56 "..\..\Areas\Code\Views\RegDoc\regdocCourriel.cshtml"
      Write(qq.FileNameI == null ? "" : string.Format("<a href='http://{0}/code/regdoc/getfilei?data={1}'>Файл</a>", host, System.Web.HttpUtility.UrlEncode(qq.FileNameI)));

            
            #line default
            #line hidden
            
            #line 56 "..\..\Areas\Code\Views\RegDoc\regdocCourriel.cshtml"
                                                                                                                                                                        Write(qq.LotusLinkI == null ? "" : string.Format(" <a href='{0}'>Документ Lotus Notes</a>", System.Web.HttpUtility.HtmlEncode(qq.LotusLinkI)));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 57 "..\..\Areas\Code\Views\RegDoc\regdocCourriel.cshtml"
     Write(qq.Comment);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    </tr>\r\n");

            
            #line 59 "..\..\Areas\Code\Views\RegDoc\regdocCourriel.cshtml"
  }

            
            #line default
            #line hidden
WriteLiteral("</table>\r\n<p");

WriteLiteral(" style=\"color: white; font-style: italic\"");

WriteLiteral(">");

            
            #line 61 "..\..\Areas\Code\Views\RegDoc\regdocCourriel.cshtml"
                                       Write(email);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

        }
    }
}
#pragma warning restore 1591
